In [1]:
!pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple


In [2]:
import numpy as np

In [3]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(a[0])

[1 2 3 4]


In [9]:
a = np.array([1, 2, 3])

In [10]:
a

array([1, 2, 3])

In [11]:
np.zeros(2)

array([0., 0.])

In [12]:
np.ones(2)

array([1., 1.])

In [13]:
np.empty(2) 

array([1., 1.])

In [14]:
a

array([1, 2, 3])

In [15]:
np.empty(2) 

array([1., 1.])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [18]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [20]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [21]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [24]:
a
b

array([5, 6, 7, 8])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
b

array([5, 6, 7, 8])

In [28]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [30]:
x

array([[1, 2],
       [3, 4]])

In [31]:
y

array([[5, 6]])

In [32]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [34]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [35]:
array_example.ndim

3

In [36]:
array_example.size

24

In [37]:
array_example.shape

(3, 2, 4)

In [38]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [39]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [40]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [42]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [43]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [44]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [46]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [47]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [49]:
data= np.array([1, 2, 3])

In [50]:
data[1]

2

In [51]:
data[0:2]

array([1, 2])

In [52]:
data[1:]

array([2, 3])

In [53]:
data[-2:]

array([2, 3])

In [54]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
print(a[a < 5])

[1 2 3 4]


In [58]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [59]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [60]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [61]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [62]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [65]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [66]:
print(a[b])

[1 2 3 4]


In [67]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [68]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [71]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [73]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [74]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [75]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [76]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [77]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [78]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [80]:
b1 = a[0, :]
b1


array([1, 2, 3, 4])

In [81]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [82]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [84]:
data - ones

array([0, 1])

In [85]:
data * data

array([1, 4])

In [86]:
data / data

array([1., 1.])

In [87]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [88]:
b = np.array([[1, 1], [2, 2]])

In [89]:
b.sum(axis=0)

array([3, 3])

In [90]:
b.sum(axis=1)

array([2, 4])

In [91]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [92]:
data.sum()

3.0

In [93]:
data.min()

1.0

In [94]:
data.max()

2.0

In [95]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [96]:
a.sum()

4.8595784

In [97]:
a.min()

0.05093587

In [98]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [99]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
data[0, 1]

2

In [101]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [102]:
data[0:2, 0]

array([1, 3])

In [103]:
data.max()

6

In [104]:
data.min()

1

In [108]:
data.sum()

21

In [109]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [110]:
data.max(axis=0)

array([5, 6])

In [111]:
data.max(axis=1)

array([2, 5, 6])

In [112]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [113]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [114]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [115]:
np.ones(3)

array([1., 1., 1.])

In [119]:
np.zeros(3)

array([0., 0., 0.])

In [120]:
rng = np.random.default_rng() 

In [121]:
rng.random(3) 

array([0.04033198, 0.74189253, 0.79518265])

In [122]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [123]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [124]:
rng.random((3, 2)) 

array([[0.4738702 , 0.03507672],
       [0.2757794 , 0.62389525],
       [0.21167683, 0.04765653]])

In [125]:
rng.integers(5, size=(2, 4))

array([[3, 4, 3, 0],
       [4, 4, 3, 0]], dtype=int64)

In [126]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [127]:
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [128]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [129]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [130]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [131]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [132]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [133]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [134]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [136]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [137]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [141]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [142]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [149]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [150]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [151]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [152]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [153]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [154]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [155]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [156]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [157]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [158]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [159]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
